/**
 * Icon registry for navigation + data files.
 *
 * Data stays serialisable by referencing icons by *name*; this map is the only
 * place that touches the icon library, and it only imports what the navs use.
 */

import {
  Activity,
  Award,
  BadgeDollarSign,
  BarChart3,
  BookOpen,
  Building,
  Calculator,
  ClipboardList,
  Compass,
  CreditCard,
  Dumbbell,
  FilePlus,
  FileText,
  GraduationCap,
  HelpCircle,
  History,
  Info,
  Layers,
  Languages,
  LayoutDashboard,
  Library,
  Mail,
  Medal,
  Microscope,
  Play,
  Presentation,
  Radar,
  Route,
  ScanLine,
  School,
  ScrollText,
  Send,
  Settings,
  Sigma,
  Sparkles,
  TrendingUp,
  User,
  UserCheck,
  Users,
} from "lucide-react";

export const NAV_ICONS = {
  "layout-dashboard": LayoutDashboard,
  radar: Radar,
  "trending-up": TrendingUp,
  "scan-line": ScanLine,
  sigma: Sigma,
  languages: Languages,
  award: Award,
  route: Route,
  compass: Compass,
  dumbbell: Dumbbell,
  "book-open": BookOpen,
  medal: Medal,
  history: History,
  "scroll-text": ScrollText,
  user: User,
  users: Users,
  "user-check": UserCheck,
  "bar-chart-3": BarChart3,
  send: Send,
  "file-plus": FilePlus,
  "file-text": FileText,
  "clipboard-list": ClipboardList,
  library: Library,
  presentation: Presentation,
  building: Building,
  school: School,
  activity: Activity,
  settings: Settings,
  "credit-card": CreditCard,
  "graduation-cap": GraduationCap,
  layers: Layers,
  sparkles: Sparkles,
  calculator: Calculator,
  "badge-dollar-sign": BadgeDollarSign,
  "help-circle": HelpCircle,
  info: Info,
  mail: Mail,
  play: Play,
  microscope: Microscope,
};

export const navIcon = (name) => NAV_ICONS[name] ?? null;
