/**
 * Icon registry for navigation + data files.
 *
 * Data stays serialisable by referencing icons by *name*; this map is the only
 * place that touches the icon library, and it only imports what the navs use.
 */

import {
  Activity,
  Award,
  BadgeDollarSign,
  BarChart3,
  BookOpen,
  Building,
  Calculator,
  ClipboardList,
  Compass,
  CreditCard,
  Dumbbell,
  FilePlus,
  FileText,
  GraduationCap,
  HelpCircle,
  History,
  Info,
  Layers,
  Languages,
  LayoutDashboard,
  Library,
  Mail,
  Medal,
  Microscope,
  Play,
  Presentation,
  ShieldCheck,
  FileCheck2,
  ClipboardCheck,
  Bell,
  Megaphone,
  BookMarked,
  Database,
  KeyRound,
  Search,
  UserCog,
  FileSpreadsheet,
  FlaskConical,
  NotebookPen,
  Blocks,
  CalendarClock,
  ListChecks,
  SquarePen,
  MoveUp,
  MoveDown,
  Volume2,
  PanelTop,
  Pause,
  RotateCcw,
  Command,
  ArrowRight,
  ArrowUpRight,
  Check,
  XCircle,
  CircleCheck,
  Eye,
  EyeOff,
  Ban,
  Plus,
  Pencil,
  Trash2,
  ChevronUp,
  ChevronDown,
  SlidersHorizontal,
  Save,
  Lock,
  LogOut,
  TrendingDown,
  TriangleAlert,
  Clock,
  Timer,
  Download,
  Filter,
  UserPlus,
  CalendarDays,
  Hash,
  Tag,
  Percent,
  Radar,
  Route,
  ScanLine,
  School,
  ScrollText,
  Send,
  Settings,
  Sigma,
  Sparkles,
  TrendingUp,
  User,
  UserCheck,
  Users,
} from "lucide-react";

export const NAV_ICONS = {
  "layout-dashboard": LayoutDashboard,
  radar: Radar,
  "trending-up": TrendingUp,
  "scan-line": ScanLine,
  sigma: Sigma,
  languages: Languages,
  award: Award,
  route: Route,
  compass: Compass,
  dumbbell: Dumbbell,
  "book-open": BookOpen,
  medal: Medal,
  history: History,
  "scroll-text": ScrollText,
  user: User,
  users: Users,
  "user-check": UserCheck,
  "bar-chart-3": BarChart3,
  send: Send,
  "file-plus": FilePlus,
  "file-text": FileText,
  "clipboard-list": ClipboardList,
  library: Library,
  presentation: Presentation,
  building: Building,
  school: School,
  activity: Activity,
  settings: Settings,
  "credit-card": CreditCard,
  "graduation-cap": GraduationCap,
  layers: Layers,
  sparkles: Sparkles,
  calculator: Calculator,
  "badge-dollar-sign": BadgeDollarSign,
  "help-circle": HelpCircle,
  info: Info,
  mail: Mail,
  play: Play,
  microscope: Microscope,
  "shield-check": ShieldCheck,
  "file-check-2": FileCheck2,
  "clipboard-check": ClipboardCheck,
  bell: Bell,
  megaphone: Megaphone,
  "book-marked": BookMarked,
  database: Database,
  "key-round": KeyRound,
  search: Search,
  "user-cog": UserCog,
  "file-spreadsheet": FileSpreadsheet,
  "flask-conical": FlaskConical,
  "notebook-pen": NotebookPen,
  blocks: Blocks,
  "calendar-clock": CalendarClock,
  "list-checks": ListChecks,
  "square-pen": SquarePen,
  "move-up": MoveUp,
  "move-down": MoveDown,
  "volume-2": Volume2,
  pause: Pause,
  "panel-top": PanelTop,
  "rotate-ccw": RotateCcw,
  command: Command,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  check: Check,
  "x-circle": XCircle,
  "circle-check": CircleCheck,
  eye: Eye,
  "eye-off": EyeOff,
  ban: Ban,
  plus: Plus,
  pencil: Pencil,
  "trash-2": Trash2,
  "chevron-up": ChevronUp,
  "chevron-down": ChevronDown,
  "sliders-horizontal": SlidersHorizontal,
  save: Save,
  lock: Lock,
  "log-out": LogOut,
  "trending-down": TrendingDown,
  "triangle-alert": TriangleAlert,
  clock: Clock,
  timer: Timer,
  download: Download,
  filter: Filter,
  "user-plus": UserPlus,
  "calendar-days": CalendarDays,
  hash: Hash,
  tag: Tag,
  percent: Percent,
};

export const navIcon = (name) => NAV_ICONS[name] ?? null;
